
samples: ../conf/samples.tsv
units: ../conf/units.tsv
patients: ../conf/patients.tsv
reheader: ../conf/reheader.tsv
sets: ../conf/sets.tsv

fastq_numb: 2

references:
    basepath: "path_to_references_data"
    provider: "reference_provider"
    release: "reference_release"
genome_fasta: "_genome_fasta"
known_variants:
    dbsnp: "known_variants/dbSNP146_chr.vcf"
    hapmap: "known_variants/hapmap_3.3.hg19.sites.vcf"
    g1k: "known_variants/1000G_phase1.snps.high_confidence.hg19.sites.vcf"
    omni: "known_variants/1000G_omni2.5.hg19.sites.vcf"
    mills: "known_variants/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf"
    ph1_indels: "known_variants/1000G_phase1.indels.hg19.sites.vcf"

tmp_dir: "path_to_tmp_dir"

interval_list: "/ELS/els9/users/biosciences/projects/niasmic/niasmic.bed"
pon: "resources/panelofnormals.vcf"
germline: "resources/af-only-gnomad.vcf.gz"
exac: "resources/small_exac_common_3.vcf.gz"
funcotator:
depthofcov_intervals: "/ELS/els9/users/biosciences/projects/niasmic/hg19_refseq_select.refseq"
bait: "/ELS/els9/users/biosciences/references/niasmic/niasmic_panel_BAITS.interval_list"
target: "/ELS/els9/users/biosciences/references/niasmic/niasmic_panel_TARGET.interval_list"
db_suffix: "db_suffix"


rules:
    bwa-mem:
        arguments: "-M"
        platform: "illumina"
    multiqc:
        arguments: "--force --interactive --cl_config 'max_table_rows: 700'"
    trim_galore_pe:
        arguments: "--paired -q 20 --fastqc --fastqc_args '--outdir qc/fastqc --quiet'"
        arguments_100: "--hardtrim5 100 "
    trim_galore_se:
        arguments: "-q 20 --fastqc --fastqc_args '--outdir qc/fastqc --quiet'"
    picard_MarkDuplicates:
        arguments: "REMOVE_DUPLICATES=false ASSUME_SORTED=true CREATE_INDEX=true"
    picard_WGSMetrics:
        arguments: "MINIMUM_MAPPING_QUALITY=-1 MINIMUM_BASE_QUALITY=-1 READ_LENGTH=150 COUNT_UNPAIRED=true"
    picard_gc:
        params: ""
    gatk_BQSR:
        known_sites:
            - dbsnp
            - mills
            - ph1_indel
    gatk_SelectVariants:
        arguments: [
                   ["--exclude-filtered", ""],
                   ["--exclude-non-variants", ""]
                   ]
    kggseq:
        arguments: [
                   ["--db-gene", "refgene,gencode,knowngene,ensembl"],
                   ["--splicing", "13"],
                   ["--neargene", "1000"],
                   ["--db-filter", "1kg201305,ESP6500AA,ESP6500EA,dbsnp141,dbsnp138,exac,gadexome,gadgenome"],
                   ["--rare-allele-freq", "1.1"],
                   ["--db-score", "dbnsfp"],
                   ["--mendel-causing-predict", "best"],
                   ["--genome-annot", ""],
                   ["--omim-annot", ""],
                   ["--cosmic-annot", ""],
                   ["--mouse-pheno", ""],
                   ["--zebrafish-pheno", ""],
                   ["--ddd-annot", ""],
                   ["--superdup-annot", ""],
                   ["--scsnv-annot", ""],
                   ["--dgv-cnv-annot", ""]
                   ]
        cmd: "java -Djava.awt.headless=true -jar path_to_software/kggseq-1.0/kggseq.jar"
        ped_file: "path_to_ped_file"
    tabix:
        params: "-s1 -b2 -e2"
    format_annotation:
        blocks_file: "../resources/annot.blocks"
    bcftools_annotate_remove:
        params: "-x INFO/ReferenceAlternativeAllele,INFO/rsID,INFO/SIFT_score,INFO/Polyphen2_HDIV_score,INFO/Polyphen2_HVAR_score,INFO/LRT_score,INFO/MutationTaster_score,INFO/MutationAssessor_score,INFO/FATHMM_score,INFO/PROVEAN_score,INFO/M-CAP_score,INFO/MutPred_score,INFO/CADD_raw,INFO/fathmm-MKL_coding_score,INFO/Eigen-raw,INFO/VEST3_score,INFO/GenoCanyon_score,INFO/integrated_fitCons_score,INFO/MetaSVM_score,INFO/clinvar_trait,INFO/clinvar_golden_stars,INFO/DiseaseCausalProb_ExoVarTrainedModel,INFO/IsRareDiseaseCausal_ExoVarTrainedModel,INFO/BestCombinedTools:OptimalCutoff:TP:TN,INFO/GeneMIMid,INFO/DGVIDs,INFO/DS,INFO/END,INFO/InbreedingCoeff,INFO/MLEAC,INFO/MLEAF,INFO/NEGATIVE_TRAIN_SITE,INFO/POSITIVE_TRAIN_SITE,INFO/RAW_MQ,INFO/SOR,INFO/VQSLOD,INFO/culprit,INFO/BaseQRankSum,INFO/ClippingRankSum,INFO/ExcessHet,INFO/FS,INFO/HaplotypeScore,INFO/MQRankSum,INFO/ReadPosRankSum"
    bedtools_coverage:
        params: ""
    mutect:
        params: "--disable-read-filter MateOnSameContigOrNoMappedMateReadFilter --disable-read-filter NotDuplicateReadFilter --disable-read-filter NotSecondaryAlignmentReadFilter" #strange: "--genotype-germline-sites true"
    vep:
        arguments: [
                   ["--sift p --polyphen p --gene_phenotype --regulatory", ""],
                   ["--uniprot --ccds --symbol --protein --tsl --canonical --mane --domains --biotype --pick_order canonical,refseq,biotype,ccds,rank,appris,tsl", ""],
                   ["--check_existing --clin_sig_allele 1 --max_af --af_gnomad --pubmed --variant_class ", ""],
                   ]
        cache_dir: "path/to/vep"
        species: "homo_sapiens"
        assembly: "GRCh37"
    filter_vep:
        arguments: ""
    bcftools_remove:
        fields_to_remove: ""
    vcf_to_tabular:
        params: ""
    vep_to_tsv:
        fields: ""


